DjangoWebProject2/urls.py
"""
Definition of urls for DjangoWebProject2.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin #для админ раздела
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf.urls import url
#from django.conf.urls import include #для админ раздела
admin.autodiscover() #для инициализации административного раздела

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('Links/', views.links, name='links'),
    
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Авторизация',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    url(r'^anketa$',views.anketa, name='anketa'),
    #url(r'^admin/', include(admin.site.urls)), # в задании написано, что это для входа в административный раздел, но это не работает, поскольку уже была добавлена строка для админ раздела выше
    url(r'^registration$', views.registration, name='registration'),
    url(r'^blog', views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', views.blogpost, name='blogpost'),
    url(r'^newpost$', views.newpost, name='newpost'),
    url(r'^videopost$', views.videopost, name='videopost')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#для загрузки файлов в папку media
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class AnketaForm (forms.Form):
    name = forms.CharField(label='Ваше имя ', min_length=2,max_length=50)
    vozrast = forms.ChoiceField(label='Ваш возраст ',
                             choices = (('1','меньше 14'), ('2','от 14 до 18'), ('3','от 18 до 30'), 
                                        ('4','от 30 до 50'), ('5','больше 50')), initial=3)
    gender = forms.ChoiceField(label='Ваш пол ',
                            choices = [('1','муж'), ('2','жен')],widget=forms.RadioSelect , initial=1)
    nalichie_sobaki = forms.ChoiceField(label='Есть ли у вас собака? ',
                            choices = [('1','да'), ('2','нет'),('3','хочу завести питомца')],widget=forms.RadioSelect , initial=1)
    poroda = forms.ChoiceField(label='Какой породы ваша собака или какую породу хотели бы завести? ',
                             choices = (('1','Аляскинский маламут'), ('2','Бигль'), ('3','Двор-терьер'), 
                                        ('4','Питбуль'), ('5','Амстаф'), ('6','Бульдог'), ('7','Датский/немецкий дог'),
                                        ('8','Афганская борзая'),('9','Пудель королевский'),('10','Пудель карликовый')), initial=1)
    rassilka = forms.BooleanField(label='Хотели бы вы получать рассылку на e-mail? ',required = False)
    email = forms.EmailField(label='Ваш e-mail? ', min_length=7)
    pogelania = forms.CharField(label='Пожелания для нашего сайта ', widget=forms.Textarea(attrs={'rows':10,'cols':20}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description','content','image')
        labels = {'title':"Заголовок",'description':"Краткое содержание",'content':"Полное содержание",'image':"Картинка"}

app/templates/app/Links.html
<!DOCTYPE html>

<html lang="ru" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="Windows-1251" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Полезные ресурсы</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Породы собак - Полезные ресурсы</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О пректе</a></li>
                    <li><a href="{% url 'contact' %}">Конаткты</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %} {% load staticfiles %}
        <a href ="https://lapkins.ru/dog/" target="_blank"> <img src="{% static 'app/content/пример 1.PNG' %}" alt="" width="150"/></a>
        <a href ="https://petsi.net/" target="_blank"> <img src="{% static 'app/content/пример 2.png' %}" alt="" width="150"/></a>
        <a href ="https://xn--80atyad7e.xn--p1ai/%D0%9F%D0%BE%D1%80%D0%BE%D0%B4%D1%8B" target="_blank"> <img src="{% static 'app/content/пример 3.png' %}" alt="" width="150"/></a>
        {% endblock %}
        <hr />
        <footer>
            <p>&copy; 2021 - Породы собак</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{title}}</h2> <br/>

{% for post in posts %}
<hr/>
<div class="">
<h2>{{post.title}}</h2>
<h4>{{post.posted}}</h4>
<p>{{post.description}}</p>
<p><a href="{% url 'blogpost' parametr=post.id %}">Читать далее...</a></p>
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}

{% load staticfiles %}

<p><a href="{% url 'blog'%}">Назад</a></p>
<h2>{{post_1.title}}</h2>

{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
    <img src="{{post_1.image.url}}" alt="Картинка" width="300" height="200">
{% endif %}

<p>{{post_1.content|linebreaksbr}}</p> <!--вывод по абзацам-->

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>
{% else %}
    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}
    

{% for comment in comments %}
    <hr/>
    <h7> {{comment.date}} </h7>
    <h5> {{comment.author}} </h5>
    <p> {{comment.text|linebreaksbr}} </p>
{% endfor %}


<p><a href="{% url 'blog'%}">Назад</a></p>
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/index.html
<meta charset="Windows-1251" />

{% extends "app/layout.html" %}


{% block content %}

<div class="jumbotron">
    <h2>Лабораторка №9</h2>
    <p class="lead"></p>
    
</div>

{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/8085b70e8b6927e1575618884.jpg'%} " alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Собачка раз
                    <a class="btn btn-default" href=""><!-- https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409 -->
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/-lg!owg.jpg'%}" alt="Второй слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Собачка два
                    <a class="btn btn-default" href="">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/3@2x.jpg'%} " alt="Третий слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Собачка три
                    <a class="btn btn-default" href="">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="row">
    <div class="col-md-4"> <!-- колонка -->
        <h2>...</h2>
        <p>
            ...
        </p>
    </div>
 
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="Windows-1251" /> <!-- была utf-8, из-за нее была ошибка при переименовании полей на странице-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
    {% load staticfiles %}
    <!--<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />-->
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Породы собак</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li> 
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'about' %}">О пректе</a></li>
                    <li><a href="{% url 'contact' %}">Конаткты</a></li>
                    <li><a href="{% url 'anketa' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
                    
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; 2021 - Породы собак</p>
        </footer>
    </div>

    
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
<html lang="ru" xmlns="http://www.w3.org/1999/xhtml">
    {% extends "app/layout.html" %}

<head>
    <meta charset="Windows-1251" />
</head>
<body>
{% block content %}
<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Введиле логин и пароль для авторизации на сайте.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Введенные данные не корректны.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}
</body>
</html>

app/templates/app/loginpartial.html
<head>
<meta charset="Windows-1251" />
</head>
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">{{ user.username }}!</span></li> <!---->
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
    <li><a href="{% url 'registration' %}">Регистрация</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data">{% csrf_token %} 
    <div>
        {{blogform.as_p}}
        <button type="submit" class="save btn btn-default">Сохранить статью</button>
    </div>
</form>

{% endblock %}

app/templates/app/pool.html
<!DOCTYPE html>

<html lang="ru" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="Windows-1251" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Обратная связь</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Породы собак - Обратная связь</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'about' %}">О пректе</a></li>
                    <li><a href="{% url 'contact' %}">Конаткты</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %} {% load staticfiles %}
        {% if form != None %} <!--если форма не пустая-->
        <br><h2>Заполните, пожалуйста, предложенную анкету и отправьте нам</h2><br>
        <div>
            <form method="post">
            {% csrf_token %} <!--без понятия кто это-->
            <label for="{{form.name.id_for_label}}">{{form.name.label}}:</label>
                {{form.name}}<br><br><!--перенос строки-->
            <label for="{{form.vozrast.id_for_label}}">{{form.vozrast.label}}:</label>
                {{form.vozrast}}<br><br>
            <label for="{{form.gender.id_for_label}}">{{form.gender.label}}:</label>
                {{form.gender}}
            <label for="{{form.nalichie_sobaki.id_for_label}}">{{form.nalichie_sobaki.label}}:</label>
                {{form.nalichie_sobaki}}
            <label for="{{form.poroda.id_for_label}}">{{form.poroda.label}}:</label>
                {{form.poroda}}<br><br>
            <label for="{{form.rassilka.id_for_label}}">{{form.rassilka.label}}:</label>
                {{form.rassilka}}<br><br>
            <label for="{{form.email.id_for_label}}">{{form.email.label}}:</label>
                {{form.email}}<br><br>
            <label for="{{form.pogelania.id_for_label}}">{{form.pogelania.label}}:</label>
                <br>
                {{form.pogelania}}<br><br>
            <input type="submit" value="Отправить" id="b1"><!--кнопка-->
            </form>
        </div>
        {% else %}
        <br><h2>Благодарим за предоставленную информацию!</h2>
        <h3>Предоставленная вами информация:</h3>
        <ul>
            <li><span>Имя: </span>{{data.name}}</li>
            <li><span>Возраст: </span>{{data.vozrast}}</li>
            <li><span>Пол: </span>{{data.gender}}</li>
            <li><span>Есть ли собака: </span>{{data.nalichie_sobaki}}</li>
            <li><span>Порода: </span>{{data.poroda}}</li>
            <li><span>Получать расслыку на e-mail: </span>{{data.rassilka}}</li>
            <li><span>E-mail: </span>{{data.email}}</li>
            <li><span>Пожелания: </span>{{data.pogelania}}</li>
        </ul>
        {% endif %}
        {% endblock %}
        <hr />
        <footer>
            <p>&copy; 2021 - Породы собак</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>

    <script>
        function p11()
        {
                $('#id_name').css('background-color', 'LightCyan');
        }
        function p12()
        {
                $('#id_name').css('background-color', 'transparent');
        }
        function p21()
        {
            $('#id_email').css('background-color', 'MediumSlateBlue');
            $('#id_email').css('color', 'White');
        }
        function p22()
        {
            $('#id_email').css('background-color', 'transparent');
            $('#id_email').css('color', 'Black');
        }
        function p31()
        {
            $('#b1').css('background-color', 'DarkMagenta');
            $('#b1').css('color', 'White');
        }
        function p32()
        {
            $('#b1').css('background-color', 'transparent');
            $('#b1').css('color', 'Black');
        }
        $('#id_name').focus(p11);
        $('#id_name').blur(p12);
        $('#id_email').focus(p21);
        $('#id_email').blur(p22);
        $('#b1').mouseover(p31);
        $('#b1').mouseout(p32);
    </script>

    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
    <h2>Регистрация пользователя</h2>
    <form method="POST" > {% csrf_token %}
        <div>
            {{ regform.as_p}}
            <button type="submit" class="save btn btn-default" > Зарегистрироваться </button>
        </div>
    </form>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}

<div>
    <h1>Видосик 1</h1>
    <video src="/media/video.mp4" controls="controls" width="400" height="300" poster="/media/заставка.jpg"></video>
</div>
<hr/>
<div>
    <h1>Видосик 2</h1>
    <video src="/media/Pexels Videos 2796080.mp4" controls="controls" width="400" height="300" poster="/media/заставка.jpg"></video>
</div>

{% endblock %}